Updated API to consider power of device. Now outputs a lbs value of CO2e
tsdataclinic/watttime-python-client-aer-algo pull request #21
Opened 2024-07-26 18:20 UTC by AzureFractal

2024-07-26 19:24 UTC, CGe0516 commented on watttime/api.py
> +        if moer_data_override is None:
Does this work both with moer forecast data and actual moer data?

2024-07-26 19:24 UTC, CGe0516 commented on watttime/api.py
>          if optimization_method == "sophisticated":
Can you provide some addl context on what this "sophisticated" methodology does? What is the buffer period for?

2024-07-26 19:25 UTC, CGe0516 commented on watttime/api.py
> +            def emission_multiplier_fn(sc, ec):
What are sc and ec here?

2024-07-26 19:25 UTC, CGe0516 commented on watttime/shared_anniez/alg/optCharger.py
> +        emission_multipliers = []
Can you provide some addl context here?

2024-07-27 02:52 UTC, asyz8 commented on watttime/api.py
> +        if moer_data_override is None:
This question is for @AzureFractal

2024-07-27 02:58 UTC, asyz8 commented on watttime/api.py
> +            def emission_multiplier_fn(sc, ec):
emission multiplier fn really provides the average energy consumption per interval between charge = sc (starting charge) and charge = ec (ending charge), where `0 <= sc <= ec <= total_charge_units = usage_time_required_minutes // OPT_INTERVAL` are integers

2024-07-27 03:18 UTC, asyz8 requested changes

2024-07-27 03:18 UTC, asyz8 commented on watttime/api_test.py
> +    columns=["time", "power_kwh"]
this should say power_kW instead of power_kWh? kW is a power unit

2024-07-27 03:18 UTC, asyz8 commented on watttime/api.py
>          if optimization_method == "sophisticated":
sophisticated means the DP algorithm. See Assumptions google sheets for the description. 

buffer is added by @AzureFractal. It requires that we finish charging early, by total_time - usage_time_uncertainty_minutes rather than using the whole period.

2024-07-27 03:18 UTC, asyz8 commented on watttime/api.py
> +                value = usage_power_kw[sc:max(sc, ec-1e-12)]["power_kwh"].mean() * 0.001 * OPT_INTERVAL / 60.0
power_kw is better

2024-07-27 03:18 UTC, asyz8 commented on watttime/shared_anniez/alg/optCharger.py
>              if emission_multiplier_fn is None:
remove this because of L269

2024-07-27 03:18 UTC, asyz8 commented on watttime/shared_anniez/alg/optCharger.py
> +        elif not self.emissionOverhead and ra<TOL and not constraints and totalIntervals <= 0:
we need to add a check here that emission_multiplier_fn is constant. otherwise we can't call the simple algorithm

2024-07-27 03:18 UTC, asyz8 commented on watttime/api.py
>                      )
not here but in return, should add two columns 
- energy consumed
- emission based on emission rate forecasts

2024-07-30 21:52 UTC, jbadsdata commented on watttime/api.py
>          )
@asyz8 I believe this parameter must be set to False to use the simple fit optimization method. So this must be something like below, where if sophisticated = False and asap = False, then the fit is simple?

```
m = moer.Moer(
        mu = moer_values, 
        isDiagonal = emissionOverheard,
        sig2 = 0.0,
)
```

2024-07-31 14:40 UTC, AzureFractal commented on watttime/api.py
> +        if moer_data_override is None:
Basically we will allow passing in a moer_data_override that has the same format as the output of get_forecast_pandas. If someone passes this in, it will be used instead of the live moer data

2024-07-31 14:45 UTC, AzureFractal commented on watttime/api_test.py
> +    columns=["time", "power_kwh"]
Fixed

2024-07-31 14:45 UTC, AzureFractal commented on watttime/api.py
> +                value = usage_power_kw[sc:max(sc, ec-1e-12)]["power_kwh"].mean() * 0.001 * OPT_INTERVAL / 60.0
FIxed

2024-07-31 14:47 UTC, AzureFractal commented on watttime/shared_anniez/alg/optCharger.py
> +        elif not self.emissionOverhead and ra<TOL and not constraints and totalIntervals <= 0:
My logic here is that we might want to be able to call simple_fit even on problems with non-constant emission functions. This would still output the right accounting for emissions but just use a simpler logic for optimizing

2024-07-31 14:55 UTC, AzureFractal commented on watttime/api.py
>                      )
Fixed

2024-07-31 15:12 UTC, AzureFractal commented on watttime/shared_anniez/alg/optCharger.py
> +        elif not self.emissionOverhead and ra<TOL and not constraints and totalIntervals <= 0:
Resolved as discussed

2024-07-31 21:15 UTC, jbadsdata commented on watttime/api.py
>          return result_df
@AzureFractal @asyz8 Currently, for testing against synthetic data, we take the output of model.get_schedule(), and historic actuals to calculate actual emissions (as opposed to the total emissions calculated against forecast). Is the usage column of the results_df the same as would have previously been returned by model.get_schedule()? If so, then the API could be used for testing against synthetic data.

2024-08-02 18:29 UTC, CGe0516 commented on watttime/api.py
>          return result_df
I was also thinking about this, I think we should be able to calculate actual emissions with the resulting 'usage' column, but may be good to add a func that makes that easier.

2024-08-02 18:36 UTC, CGe0516 commented on watttime/api.py
>          if optimization_method == "sophisticated":
So I see that this buffer is being added to `constraints`. Can you describe when you would use this parameter? In my mind, to enforce this buffer time, the simplest solution would just be to shorten the end time so that you finish charging early?

2024-08-02 18:56 UTC, CGe0516 commented on watttime/api.py
> +            def emission_multiplier_fn(sc, ec):
So looks to me like we're reformatting usage_power_kw to be spaced by OPT_INTERVAL. Does this currently handle cases when changes in usage_power_kw don't align with the intervals? e.g. if the input was 

> usage_power_kw_df = pd.DataFrame(
>     [[0, 12], [100, 12], [217, 12], [320, 2.4]],
>     columns=["time", "power_kw"]
> )

2024-08-09 17:09 UTC, jbadsdata commented
@AzureFractal is this ready to be merged into develop?

2024-08-09 17:14 UTC, AzureFractal commented on watttime/api.py
>          return result_df
This has been updated in the latest commit

2024-08-09 17:15 UTC, AzureFractal commented on watttime/api.py
> +            def emission_multiplier_fn(sc, ec):
Currently takes the last known value and doesn't interpolate. Could introduce it as an action item

2024-08-09 17:16 UTC, AzureFractal commented on watttime/api.py
>          if optimization_method == "sophisticated":
Yes, I think it would be basically the same thing, but without the user manually touching the contraints. I think for now it's fine but we can update this with something more sophisticated later. We could also consider how many SDs of uncertainty to account for too.

2024-08-09 17:24 UTC, CGe0516 commented on watttime/api.py
> +            def emission_multiplier_fn(sc, ec):
Gotcha, can you add a note about this? this ex. is from api_test.py so maybe we should also switch that as well.

2024-08-09 17:34 UTC, merged